name: Package Nuget Module

on:
  push:
    branches: [main]

jobs:
  test-and-package:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: atm

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test:cov

      - name: Build Package
        run: npm pack ./libs/domain

      - name: Rename Package
        run: mv bank_domain_viveros-1.0.0.tgz bank_domain_viveros.tgz

      # Simulated publish to GitHub nuget Registry
      - name: Simulated Publish to GitHub Packages
        run: echo "Simulating publish of atm_viveros.tgz to registry"
