name: Release Version

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: atm

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Package
        run: npm pack ./libs/atm

      - name: Rename Package
        run: mv atm-0.0.1.tgz atm_viveros.tgz

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: atm_viveros.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
